// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ReadBrendaFile
std::vector<std::string> ReadBrendaFile(const std::string& filepath);
RcppExport SEXP _brendaDb_ReadBrendaFile(SEXP filepathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type filepath(filepathSEXP);
    rcpp_result_gen = Rcpp::wrap(ReadBrendaFile(filepath));
    return rcpp_result_gen;
END_RCPP
}
// SeparateEntries
std::vector<std::vector<std::string>> SeparateEntries(const std::vector<std::string>& lines);
RcppExport SEXP _brendaDb_SeparateEntries(SEXP linesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<std::string>& >::type lines(linesSEXP);
    rcpp_result_gen = Rcpp::wrap(SeparateEntries(lines));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_brendaDb_ReadBrendaFile", (DL_FUNC) &_brendaDb_ReadBrendaFile, 1},
    {"_brendaDb_SeparateEntries", (DL_FUNC) &_brendaDb_SeparateEntries, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_brendaDb(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
