# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
read_brenda_file <- function(filepath) {
    .Call('_brendaDb_read_brenda_file', PACKAGE = 'brendaDb', filepath)
}

