#' @title Read BRENDA text file into matrix.
#'
#' @inherit SeparateEntries return description
#'
#' @inheritParams ReadBrendaFile
#' @param clean Boolean; if TRUE, run [CleanECNumber()] after reading the file.
#'
#' @return A matrix containing information about the EC entries.
#'
#' @examples
#' brenda_txt <- system.file("extdata", "brenda_download_test.txt",
#'                           package = "brendaDb")
#' df <- ReadBrenda(brenda_txt)
#'
#' @importFrom magrittr %>%
#' @importFrom tibble as_tibble
#' @importFrom dplyr distinct
#' @export
ReadBrenda <- function(filepath, clean = TRUE) {
  # src/read_brenda
  message("Reading BRENDA text file...")
  filepath <- path.expand(filepath)
  df <- ReadBrendaFile(filepath)

  message("Converting text into a list. This might take a while...")
  df <- SeparateEntries(df)
  names(df) <- c("ID", "field", "description")

  message("Converting list to tibble and removing duplicated entries...")
  df <- df %>%
    as_tibble() %>%
    distinct()
  if (clean) {
    df <- CleanECNumber(df)
  }
  return(df)
}


#' @title Remove deleted and transferred EC numbers.
#'
#' @description Some EC numbers have comments wrapped in parentheses. Most of
#' them are deleted (in this case we remove them) entries or transferred (in
#' this case we point to the new entry) entries.
#'
#' @param df A `tibble` generated by [ReadBrenda()].
#'
#' @return A `tibble` with deleted and transferred entries moved to the bottom,
#' with columns:
#' - ID being the deleted/transferred ID,
#' - field being "TRANSFERRED_DELETED", and
#' - description being the information included in the original ID column.
#'
#' @examples
#' df <- ReadBrenda(system.file("extdata", "brenda_download_test.txt",
#'                           package = "brendaDb"))
#' brendaDb:::CleanECNumber(df)
#'
#' @importFrom dplyr mutate filter bind_rows
#' @importFrom rlang .data
#' @import stringr
CleanECNumber <- function(df) {
  df <- df %>%
    mutate(ID = str_remove(.data$ID, regex(" \\(\\)", fixed = TRUE)))
  df.standard <- df %>%
    filter(str_detect(.data$ID, regex("\\(", fixed = TRUE), negate = TRUE))
  df.nonstd <- df %>%
    filter(str_detect(.data$ID, regex("\\(", fixed = TRUE))) %>%
    distinct(.data$ID) %>%
    mutate(
      field = "TRANSFERRED_DELETED",
      description = str_sub(str_extract(.data$ID, "\\(.*$"), 2, -2),
      ID = str_extract(.data$ID, "^(\\d+\\.){3}\\d+")
    ) %>%
    filter(!is.na(.data$ID))
  return(bind_rows(df.standard, df.nonstd))
}


#' @title Download the BRENDA text file.
#'
#' @param path The path to store the downloaded text file.
#' @param ... Parameters to be passed to `unzip`.
#'
#' @return A text file downloaded to `path`.
#' @export
#'
#' @examples \dontrun{DownloadBrenda("/path/to/textfile")}
#'
#' @importFrom utils download.file unzip
DownloadBrenda <- function(path = "./brenda_download.zip", ...) {
  download.file(
    url = "https://s3.us-east-2.amazonaws.com/brendadb-r-package/brenda_download.zip",
    destfile = path
    )
  unzip(path, ...)
}
